# Generated by Django 6.0.2 on 2026-02-23 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('Licence', 'Licence'), ('Master', 'Master'), ('DUT', 'DUT'), ('Doctorat', 'Doctorat'), ('BTS', 'BTS')], max_length=20)),
                ('duree', models.PositiveIntegerField(default=3)),
                ('frais_inscription', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('licence', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PRO', 'Pro')], default='STANDARD', max_length=20)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendu', 'Suspendu'), ('expire', 'Expiré')], default='active', max_length=20)),
                ('date_expiration_licence', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Université',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administration'), ('professeur', 'Enseignant'), ('etudiant', 'Étudiant')], default='etudiant', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('specialite', models.CharField(max_length=200)),
                ('grade', models.CharField(choices=[('assistant', 'Assistant'), ('maitre_assistant', 'Maître-Assistant'), ('maitre_conferences', 'Maître de Conférences'), ('professeur_titulaire', 'Professeur Titulaire')], default='maitre_assistant', max_length=30)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('conge', 'Congé'), ('inactif', 'Inactif')], default='actif', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enseignants/')),
                ('date_recrutement', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL)),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='api.universite')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('niveau', models.CharField(default='L1', max_length=10)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('reinscrit', 'Réinscrit'), ('bloque', 'Bloqué'), ('diplome', 'Diplômé'), ('abandon', 'Abandon')], default='inscrit', max_length=20)),
                ('solde_du', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='etudiants/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='api.anneeacademique')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='api.filiere')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='api.universite')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], default=1)),
                ('niveau', models.CharField(default='L1', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres', to='api.enseignant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='api.filiere')),
            ],
            options={
                'ordering': ['semestre', 'nom'],
                'unique_together': {('filiere', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salle', models.CharField(max_length=50)),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('semaine', models.CharField(choices=[('toutes', 'Toutes'), ('paire', 'Paire'), ('impaire', 'Impaire')], default='toutes', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois', to='api.anneeacademique')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois', to='api.matiere')),
            ],
            options={
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notif', models.CharField(choices=[('info', 'Info'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Danger')], default='info', max_length=20)),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=30, unique=True)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Mobile Money (Orange)'), ('moov_money', 'Mobile Money (Moov)'), ('virement', 'Virement Bancaire'), ('cheque', 'Chèque')], max_length=30)),
                ('type_paiement', models.CharField(choices=[('inscription', 'Inscription'), ('reinscription', 'Réinscription'), ('acompte', 'Acompte'), ('solde', 'Solde'), ('autre', 'Autre')], default='inscription', max_length=20)),
                ('statut', models.CharField(choices=[('valide', 'Validé'), ('en_attente', 'En attente'), ('rejete', 'Rejeté')], default='valide', max_length=20)),
                ('reference_mobile', models.CharField(blank=True, max_length=50)),
                ('date_paiement', models.DateField()),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.anneeacademique')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.etudiant')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SupportCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_support', models.CharField(choices=[('cours', 'Cours magistral'), ('td', 'TD'), ('tp', 'TP'), ('examen_corrige', 'Examen corrigé'), ('ressource', 'Ressource complémentaire')], default='cours', max_length=30)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='supports/')),
                ('description', models.TextField(blank=True)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='api.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='api.matiere')),
            ],
            options={
                'ordering': ['-date_depot'],
            },
        ),
        migrations.AddField(
            model_name='filiere',
            name='universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='api.universite'),
        ),
        migrations.AddField(
            model_name='anneeacademique',
            name='universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annees', to='api.universite'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_cc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_examen', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_rattrapage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('date_saisie', models.DateTimeField(auto_now=True)),
                ('publie', models.BooleanField(default=False)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.anneeacademique')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.matiere')),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['matiere__semestre', 'matiere__nom'],
                'unique_together': {('etudiant', 'matiere', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cours', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('justifie', models.BooleanField(default=False)),
                ('observation', models.CharField(blank=True, max_length=200)),
                ('emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='api.emploidutemps')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='api.etudiant')),
            ],
            options={
                'ordering': ['-date_cours'],
                'unique_together': {('etudiant', 'emploi', 'date_cours')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('universite', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='anneeacademique',
            unique_together={('universite', 'libelle')},
        ),
    ]
