# Generated by Django 6.0.2 on 2026-02-24 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('note_incorrecte', 'Note incorrecte / erreur de saisie'), ('note_manquante', 'Note manquante'), ('mauvaise_matiere', 'Note attribuée à la mauvaise matière'), ('calcul_errone', 'Erreur de calcul de moyenne'), ('autre', 'Autre problème')], max_length=30)),
                ('description', models.TextField()),
                ('note_attendue', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('reponse_enseignant', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='api.etudiant')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='api.note')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réclamation de note',
                'verbose_name_plural': 'Réclamations de notes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
