# Generated by Django 6.0.2 on 2026-02-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_evaluation_noteevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('confirme', 'Confirmé par étudiant'), ('reclame', 'Réclamé par étudiant')], default='brouillon', max_length=20),
        ),
    ]
