# Generated by Django 6.0.2 on 2026-02-25 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_note_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('type_question', models.CharField(choices=[('choix_unique', 'Choix unique'), ('choix_multiple', 'Choix multiple'), ('texte', 'Texte libre'), ('note', 'Note (1-5)')], max_length=20)),
                ('ordre', models.IntegerField(default=0)),
                ('obligatoire', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Question de Sondage',
                'verbose_name_plural': 'Questions de Sondage',
                'ordering': ['sondage', 'ordre'],
            },
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administration'), ('professeur', 'Enseignant'), ('etudiant', 'Étudiant'), ('bureau_executif', 'Bureau Exécutif')], default='etudiant', max_length=20),
        ),
        migrations.CreateModel(
            name='DemandeAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('attestation', "Attestation d'inscription"), ('releve', 'Relevé de notes'), ('certificat', 'Certificat de scolarité'), ('carte', "Carte d'étudiant"), ('stage', 'Convention de stage'), ('autre', 'Autre')], max_length=20)),
                ('objet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_traitement', 'En traitement'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='api.etudiant')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande Administrative',
                'verbose_name_plural': 'Demandes Administratives',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_evenement', models.CharField(choices=[('conference', 'Conférence'), ('atelier', 'Atelier'), ('competition', 'Compétition'), ('culturel', 'Événement Culturel'), ('sportif', 'Événement Sportif'), ('social', 'Événement Social'), ('autre', 'Autre')], max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('capacite_max', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('inscription_requise', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='MembreBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(choices=[('president', 'Président(e)'), ('vice_president', 'Vice-Président(e)'), ('secretaire', 'Secrétaire Général(e)'), ('tresorier', 'Trésorier(ère)'), ('charge_communication', 'Chargé(e) de Communication'), ('charge_evenements', 'Chargé(e) des Événements'), ('charge_academique', 'Chargé(e) des Affaires Académiques'), ('membre', 'Membre')], max_length=50)),
                ('date_debut_mandat', models.DateField()),
                ('date_fin_mandat', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('biographie', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bureau/')),
                ('etudiant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre_bureau', to='api.etudiant')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membre_bureau', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre du Bureau',
                'verbose_name_plural': 'Membres du Bureau',
                'ordering': ['poste', 'utilisateur__nom'],
            },
        ),
        migrations.CreateModel(
            name='MessageBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.BooleanField(default=False)),
                ('sujet', models.CharField(blank=True, max_length=200)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Bureau',
                'verbose_name_plural': 'Messages Bureau',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ObjetPerdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_declaration', models.CharField(choices=[('perdu', 'Objet perdu'), ('trouve', 'Objet trouvé')], max_length=10)),
                ('nom_objet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lieu', models.CharField(max_length=200)),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('date_perte', models.DateField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('recupere', 'Récupéré'), ('archive', 'Archivé')], default='actif', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='objets_perdus/')),
                ('contact', models.CharField(max_length=100)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objets_declares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objet Perdu',
                'verbose_name_plural': 'Objets Perdus',
                'ordering': ['-date_declaration'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('categorie', models.CharField(choices=[('actualite', 'Actualité'), ('evenement', 'Événement'), ('annonce', 'Annonce'), ('info', 'Information'), ('urgent', 'Urgent')], max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('vues', models.IntegerField(default=0)),
                ('epingle', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OptionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.questionsondage')),
            ],
            options={
                'verbose_name': 'Option de Question',
                'verbose_name_plural': 'Options de Question',
                'ordering': ['question', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('termine', 'Terminé'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('anonyme', models.BooleanField(default=True)),
                ('multiple_reponses', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sondages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sondage',
                'verbose_name_plural': 'Sondages',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_reponse', models.TextField(blank=True)),
                ('note', models.IntegerField(blank=True, null=True)),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses_sondages', to='api.etudiant')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='api.optionquestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='api.questionsondage')),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='api.sondage')),
            ],
            options={
                'verbose_name': 'Réponse de Sondage',
                'verbose_name_plural': 'Réponses de Sondage',
                'ordering': ['-date_reponse'],
            },
        ),
        migrations.AddField(
            model_name='questionsondage',
            name='sondage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.sondage'),
        ),
        migrations.CreateModel(
            name='InscriptionEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_evenements', to='api.etudiant')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.evenement')),
            ],
            options={
                'verbose_name': 'Inscription Événement',
                'verbose_name_plural': 'Inscriptions Événements',
                'ordering': ['-date_inscription'],
                'unique_together': {('evenement', 'etudiant')},
            },
        ),
    ]
