# Generated by Django 6.0.2 on 2026-02-28 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_questionsondage_alter_utilisateur_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=10)),
                ('annee_academique', models.CharField(max_length=20)),
                ('effectif_max', models.IntegerField(default=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.filiere')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau', 'code'],
                'unique_together': {('code', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='LettreRappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lettre', models.CharField(choices=[('rappel_amiable', 'Rappel amiable'), ('mise_en_demeure', 'Mise en demeure'), ('convocation', 'Convocation administrative')], max_length=20)),
                ('contenu', models.TextField()),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='lettres_rappel/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('envoyee', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettres_rappel', to='api.etudiant')),
                ('generee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lettre de Rappel',
                'verbose_name_plural': 'Lettres de Rappel',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='EnseignementMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20)),
                ('semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')])),
                ('date_assignation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='api.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='api.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='api.matiere')),
            ],
            options={
                'verbose_name': 'Enseignement de Matière',
                'verbose_name_plural': 'Enseignements de Matières',
                'ordering': ['classe', 'matiere'],
                'unique_together': {('enseignant', 'matiere', 'classe', 'annee_academique', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('publication', 'Publication'), ('confirmation', 'Confirmation étudiant'), ('reclamation', 'Réclamation'), ('correction', 'Correction après réclamation')], max_length=20)),
                ('note_cc_avant', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_examen_avant', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('statut_avant', models.CharField(blank=True, max_length=20)),
                ('publie_avant', models.BooleanField(default=False)),
                ('note_cc_apres', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_examen_apres', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('statut_apres', models.CharField(blank=True, max_length=20)),
                ('publie_apres', models.BooleanField(default=False)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='api.note')),
            ],
            options={
                'verbose_name': 'Historique de Note',
                'verbose_name_plural': 'Historiques de Notes',
                'ordering': ['-date_modification'],
                'indexes': [models.Index(fields=['note', '-date_modification'], name='api_histori_note_id_b939cb_idx'), models.Index(fields=['modifie_par', '-date_modification'], name='api_histori_modifie_1041c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('abandonne', 'Abandonné'), ('diplome', 'Diplômé')], default='actif', max_length=20)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.etudiant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('etudiant', 'classe', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='RappelPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rappel', models.CharField(choices=[('rappel_1', 'Premier rappel (J+7)'), ('rappel_2', 'Deuxième rappel (J+15)'), ('rappel_3', 'Dernier rappel (J+30)'), ('mesure', 'Mesure administrative (J+45)')], max_length=20)),
                ('montant_du', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField()),
                ('envoye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels_paiement', to='api.etudiant')),
            ],
            options={
                'verbose_name': 'Rappel de Paiement',
                'verbose_name_plural': 'Rappels de Paiement',
                'ordering': ['-date_envoi'],
                'indexes': [models.Index(fields=['etudiant', '-date_envoi'], name='api_rappelp_etudian_3cc26c_idx')],
            },
        ),
    ]
