# Generated by Django 6.0.2 on 2026-03-06 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_notification_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LettreRappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lettre', models.CharField(choices=[('premier', 'Premier rappel'), ('deuxieme', 'Deuxième rappel'), ('final', 'Rappel final'), ('mise_en_demeure', 'Mise en demeure')], max_length=20)),
                ('montant_du', models.DecimalField(decimal_places=0, max_digits=12)),
                ('contenu', models.TextField()),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='lettres_rappel/')),
            ],
            options={
                'verbose_name': 'Lettre de Rappel',
                'verbose_name_plural': 'Lettres de Rappel',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('carte', 'Carte bancaire')], max_length=20)),
                ('numero_recu', models.CharField(max_length=50, unique=True)),
                ('date_paiement', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='valide', max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='RappelPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rappel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('notification', 'Notification app'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('montant_du', models.DecimalField(decimal_places=0, max_digits=12)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rappel de Paiement',
                'verbose_name_plural': 'Rappels de Paiement',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.RenameIndex(
            model_name='notificationemail',
            new_name='api_notific_destina_9788bc_idx',
            old_name='api_notific_destina_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationemail',
            new_name='api_notific_envoye_72245e_idx',
            old_name='api_notific_envoye_idx',
        ),
        migrations.AddField(
            model_name='lettrerappel',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettres_rappel', to='api.etudiant'),
        ),
        migrations.AddField(
            model_name='lettrerappel',
            name='generee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.anneeacademique'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.etudiant'),
        ),
        migrations.AddField(
            model_name='rappelpaiement',
            name='envoye_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rappelpaiement',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels_paiement', to='api.etudiant'),
        ),
    ]
