# Generated by Django 6.0.2 on 2026-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_restauration_paiements'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='lycee_provenance',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lycée de provenance'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='ville_origine',
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville d'origine"),
        ),
    ]
