# Generated by Django 6.0.2 on 2026-03-06 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_ajout_donnees_marketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.CharField(max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='cartes_qr/')),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée'), ('suspendue', 'Suspendue'), ('annulee', 'Annulée')], default='active', max_length=20)),
                ('code_verification', models.CharField(max_length=100, unique=True)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte_numerique', to='api.etudiant')),
            ],
            options={
                'verbose_name': 'Carte Étudiant',
                'verbose_name_plural': 'Cartes Étudiants',
                'ordering': ['-date_emission'],
            },
        ),
    ]
