# Generated by Django 6.0.2 on 2026-03-06 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_carte_etudiant_numerique'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='annee_bac',
            field=models.IntegerField(blank=True, null=True, verbose_name="Année d'obtention du BAC"),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='mention_bac',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mention'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='serie_bac',
            field=models.CharField(blank=True, max_length=50, verbose_name='Série du BAC'),
        ),
        migrations.CreateModel(
            name='DemandeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('lycee_provenance', models.CharField(max_length=200, verbose_name='Lycée de provenance')),
                ('ville_origine', models.CharField(max_length=100, verbose_name="Ville d'origine")),
                ('serie_bac', models.CharField(max_length=50, verbose_name='Série du BAC')),
                ('annee_bac', models.IntegerField(verbose_name="Année d'obtention du BAC")),
                ('mention_bac', models.CharField(blank=True, max_length=50, verbose_name='Mention')),
                ('niveau_demande', models.CharField(default='L1', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='demandes_inscription/photos/')),
                ('copie_bac', models.FileField(blank=True, null=True, upload_to='demandes_inscription/bac/')),
                ('copie_identite', models.FileField(blank=True, null=True, upload_to='demandes_inscription/identite/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de traitement'), ('en_cours', 'En cours de traitement'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_inscription', to='api.anneeacademique')),
                ('etudiant_cree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='api.etudiant')),
                ('filiere_demandee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_inscription', to='api.filiere')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'Inscription",
                'verbose_name_plural': "Demandes d'Inscription",
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('annee_entree', models.IntegerField()),
                ('annee_sortie_prevue', models.IntegerField()),
                ('effectif_initial', models.IntegerField(default=0)),
                ('effectif_actuel', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='api.filiere')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-annee_entree', 'filiere'],
                'unique_together': {('filiere', 'annee_entree')},
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='api.promotion'),
        ),
    ]
