# Generated by Django 6.0.2 on 2026-03-06 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_systeme_inscription_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeInscriptionProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('filiere_enseignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_profs', to='api.filiere', verbose_name='Filière enseignée')),
                ('professeur_cree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='api.enseignant')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profs_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'Inscription Professeur",
                'verbose_name_plural': "Demandes d'Inscription Professeurs",
                'ordering': ['-date_demande'],
            },
        ),
    ]
