# Generated by Django 6.0.2 on 2026-03-06 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_demandeinscriptionprofesseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administration'), ('communication', 'Service Communication'), ('academique', 'Service Académique'), ('comptabilite', 'Service Comptabilité'), ('professeur', 'Enseignant'), ('etudiant', 'Étudiant'), ('bureau_executif', 'Bureau Exécutif')], default='etudiant', max_length=20),
        ),
        migrations.CreateModel(
            name='DemandeInscriptionAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('poste_souhaite', models.CharField(default='Responsable académique', max_length=200)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academiques_valides', to=settings.AUTH_USER_MODEL)),
                ('utilisateur_cree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_academique_origine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande Service Académique',
                'verbose_name_plural': 'Demandes Service Académique',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='DemandeInscriptionCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('poste_souhaite', models.CharField(default='Chargé de communication', max_length=200)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_validees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur_cree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_communication_origine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande Service Communication',
                'verbose_name_plural': 'Demandes Service Communication',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='DemandeInscriptionComptabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('poste_souhaite', models.CharField(default='Comptable', max_length=200)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptabilites_validees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur_cree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_comptabilite_origine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande Service Comptabilité',
                'verbose_name_plural': 'Demandes Service Comptabilité',
                'ordering': ['-date_demande'],
            },
        ),
    ]
