# Generated by Django 6.0.2 on 2026-03-07 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_ajout_services_administratifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois', to='api.classe'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='type_cours',
            field=models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], default='CM', max_length=10),
        ),
    ]
